### ISSUE TITLE
typo: "if exist" should be "if exists"

### ISSUE THREAD

**Issue by gvwilson** [PacktPublishing/Learn-PostgreSQL-Second-Edition#1]
In discussion of `DROP ROLE` on pg 58 of paperback edition, there are several references to `IF EXIST` (singular). I believe it should be `IF EXISTS` (plural) - using your basic Docker image:

```
postgres=# drop role if exists something;
NOTICE:  role "something" does not exist, skipping
DROP ROLE
postgres=# drop role if exist something;
ERROR:  syntax error at or near "exist"
LINE 1: drop role if exist something;
                     ^
```

**Comment by fluca1978** [comment]
Dear Greg,
I confirm the typo in the book at the page 58. I've updated the errata
section <
https://github.com/PacktPublishing/Learn-PostgreSQL-Second-Edition#errata>.

Thanks,
Luca

**Comment by fluca1978** [comment]
Close via 41e6236
