### ISSUE TITLE
No forumdb database is available in standalone

### ISSUE THREAD

**Issue by subbuk987** [PacktPublishing/Learn-PostgreSQL-Second-Edition#4]
There is no forumdb database available in standalone container. The below is the preview of `\l` command.
<img width="811" alt="Screenshot 2024-10-29 at 11 07 58 AM" src="https://github.com/user-attachments/assets/0354388a-6a28-4d4a-83b3-9a07b7e8660c">

**Comment by NathanBeesley** [comment]
I see you are running docker. Here are the steps you can take to get the `forum` db in standalone.

1. cd docker-images/
2. Run bash run-pg-docker.sh - Create the standalone container
3. Run docker cp setup standalone_learn_postgresql_1:/setup - Copy the setup scripts into the container
4. Run `docker exec -it standalone_learn_postgresql_1 /bin/bash -c "sh /setup/001-create-database-users.sh"` - Runs the create user script
5. Run `docker exec -it standalone_learn_postgresql_1 psql -U postgres` - Open an interactive psql session in the container
6. \i /setup/002-forum-database.sql - Run the forum database sql file to create the forumdb.

Hope this helps!!!

**Comment by NathanBeesley** [comment]
@subbuk987 I see you are running docker. Here are the steps you can take to get the forum db in standalone docker container.

`cd docker-images/` - Go to the directory that contains the standalone bash script
Run `bash run-pg-docker.sh` - Create the standalone container
Run `docker cp setup standalone_learn_postgresql_1:/setup` - Copy the setup scripts into the container
Run `docker exec -it standalone_learn_postgresql_1 /bin/bash -c "sh /setup/001-create-database-users.sh"` - Runs the create user script
Run `docker exec -it standalone_learn_postgresql_1 psql -U postgres` - Open an interactive psql session in the container
Run `\i /setup/002-forum-database.sql` - Run the forum database sql file to create the forumdb. `\I`(include) command to run the SQL file.

Hope this helps!!!

**Comment by fluca1978** [comment]
> There is no forumdb database available in standalone container. 

The three databases `postgres` and `template0`,`template1` are the default installation. In short, something went wrong during the docker initialization. I suggest you to start from scratch deleting all the storage on the filesystem related to the docker image and let the container re-initialize itself. Otherwise, follow the suggestions from @NathanBeesley

**Comment by subbuk987** [comment]
Thanks @NathanBeesley . Your approach worked for me. Also, Thanks @fluca1978 for your swift response. I'm Enjoying the book. I'm Closing the issue.
